services:
  atlas:
    build: .
    container_name: atlas
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - atlas-data:/app/data
      - ./config.json:/app/config.json
    environment:
      - ATLAS_NNTP_HOST=news.usenet.farm
      - ATLAS_NNTP_PORT=563
      - ATLAS_NNTP_USER=
      - ATLAS_NNTP_PASS=
      - ATLAS_INDEX_MODE=dynamic
    network_mode: host

volumes:
  atlas-data:
